# spring.thymeleaf.cache=false
spring:
  datasource:
    generate-unique-name: false
    name: tacocloud
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: none
        #globally_quoted_identifiers: true
  rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: guest
    template:
      exchange: tacocloud.order
      routing-key: kitchens.central
      receive-timeout: 30000
  #Определение базового пути для REST API
  data:
    rest:
      base-path: /data-api
  sql:
    init:
      platform: h2
  #security:
  #  oauth2:
  #    client:
  #      registration:
  #        facebook:
  #          client-id:
  #          client-secret:
  #          scope:
  #            - email
  #            - public_profile
logging:
  file:
    path: /var/logs
    file: TacoCloud.log
  level:
    root: INFO
    org:
      springframework:
        security: INFO

taco:
  orders: 10
