# spring.thymeleaf.cache=false
spring:
  datasource:
    generate-unique-name: false
    name: tacocloud
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: none
        globally_quoted_identifiers: true
  sql:
    init:
      platform: h2